
# build-windows-exe.yml (v3 - La Solución Definitiva con Variables de Entorno)
# Compila el bot en un ejecutable de Windows.

name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install

      - name: Install PyInstaller
        run: pip install pyinstaller
      
      # ----- ¡LA SOLUCIÓN! SEPARAMOS LOS PASOS -----

      # Paso 6a: Ejecutar el script y guardar la ruta en una variable de entorno.
      - name: Get Playwright Path
        id: get-path # Le damos un ID a este paso
        run: echo "PLAYWRIGHT_PATH=$(python get_playwright_path.py)" >> $env:GITHUB_ENV
        shell: bash
      
      # Paso 6b: Compilar el ejecutable, usando la variable que acabamos de crear.
      - name: Build Windows executable
        run: pyinstaller --onefile --name bot_energia_playwright --add-data "${{ env.PLAYWRIGHT_PATH }}:ms-playwright" bot_playwright.py
        shell: bash

      # Paso 7: Subir el .exe final.
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/bot_energia_playwright.exe
